dataset_dir: data\downstream_tasks\DharmaBench\Tibetan\SCCT
text_fields: [text]
label_field: label
model_name: OMRIDRORI/mbert-tibetan-continual-wylie-final
# tokenizer_name: optional
convert_to_wylie: auto
num_epochs: 3
learning_rate: 2.0e-5
batch_size: 8
eval_steps: 50
save_total_limit: 2
files: [train.jsonl, test.jsonl]
f1_average: weighted


